name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        continue-on-error: true
        run: flutter analyze

      - name: Run Tests
        continue-on-error: true
        run: flutter test

      - name: Build APK
        run: flutter build apk --release
